package renderer.core.pipeline;

import renderer.controller.ImageWrapper;
import renderer.core.shader.DepthBuffer;
import renderer.core.shader.fragmentshaders.Fragment;
import renderer.core.shader.fragmentshaders.FragmentOutput;

/**
 * The OutputMerger class is responsible for the final step of the rendering pipeline.
 * 
 * It takes the fragments generated by the rasterizer and merges them into the 
 * final image, taking into account depth testing and blending.
 * 
 * @author kieliszak
 */
public class OutputMerger {

    private final ImageWrapper screen;
    private final DepthBuffer depth;

    /**
     * Creates a OutputMerger with the given ImageWrapper.
     *
     * @param screen the image wrapper to use
     */
    public OutputMerger(ImageWrapper screen) {
        this.screen = screen;
        this.depth = new DepthBuffer(screen.getWidth(), screen.getHeight());
    }


    /**
     * Test whether the fragment falls onto the screen.
     * @param fragment the fragment to test
     * @return true if the fragment is clipped, false otherwise
     */
    public boolean isClipped(Fragment fragment) {
        int x = fragment.getX();
        int y = fragment.getY();

        return x < 0 || x >= screen.getWidth() || y < 0 || y >= screen.getHeight();
    }

    public void merge(Fragment fragment, FragmentOutput out) {

        // Check if fragment is clipped (outside screen bounds)
        if (isClipped(fragment)) {
            return;
        }
        
        int x = fragment.getX();
        int y = fragment.getY();

        //++ // TODO: Test depth and write the fragment color to the screen only if it is visible
        //++ screen.setRGB(x, y, out.color().getRGB());
        //<!!
        if (depth.testFragment(fragment)) { 
            if(fragment.getAttribute(Fragment.COLOR_ALPHA) > 0.0d) {
                screen.setRGB(x, y, out.color().getRGB()); 
            }
            depth.writeFragment(fragment); 
        } //>!!
    }

    /**
     * Common entry point to re-initialize the output.
     */
    public void reset() {
        depth.clear();
    }
}

