package renderer.core.pipeline;

import renderer.algebra.Matrix;
import renderer.algebra.Vector;
import renderer.core.shader.fragmentshaders.Fragment;
import renderer.core.shader.vertexshaders.Vertex;
import renderer.algebra.SizeMismatchException;
import renderer.utils.Interpolation;
import renderer.utils.LinearInterpolator;
import renderer.utils.AttributeInterpolator;
import renderer.utils.Bresenham;

/**
 * The Rasterizer class is responsible for the discretization of geometric
 * primitives (edges and faces) over the screen pixel grid and generates Fragment 
 * (pixels with interpolated attributes). 
 * 
 * Those Fragment are then passed to a FragmentConsumer object,
 * which will produce the final color of the fragment.
 *
 * @author morin, chambon, cdehais, kieliszak
 */
public class Rasterizer {

    /**
     * The default value for interpolate between 2 points.
     */
    private static final double MIDDLE_DOUBLE_VALUE = .5;

    /** The FragmentConsumer to use */
    protected FragmentConsumer consumer;

    /**
     * Creates a Rasterizer with the given FragmentConsumer.
     *
     * @param consumer the fragment consumer to use
     */
    public Rasterizer(FragmentConsumer consumer) {
        this.consumer = consumer;
    }

    public void setConsumer(FragmentConsumer consumer) {
        this.consumer = consumer;
    }


    /**
     * Rasterizes a vertex on the screen.
     *
     * @param v the vertex drawn
     */
    public void rasterizeVertex(final Vertex v) {

        int x1 = v.x;
        int y1 = v.y;

        // For now : just display the vertices
        Fragment f = new Fragment(x1, y1);

        // Set the depth of the fragment
        f.setAttribute(Fragment.DEPTH, v.depth);

        // Set the normal of the fragment
        for(int i = 0 ; i < 3 ; i++) {
            f.setAttribute(Fragment.NORMAL_X + i, v.normal.get(i));
        }

        // Set the world position of the fragment
        for(int i = 0 ; i < 3 ; i++) {
            f.setAttribute(Fragment.WORLD_X + i, v.worldPosition.get(i));
        }

        // Set the color of the fragment
        for(int i = 0 ; i < 3 ; i++) {
            f.setAttribute(Fragment.COLOR_R + i, v.color[i]);
        }

        // Set the alpha value of the fragment
        f.setAttribute(Fragment.COLOR_ALPHA, v.alpha);

        // Set the UV coordinates of the fragment
        f.setAttribute(Fragment.TEXTURE_U, v.u);
        f.setAttribute(Fragment.TEXTURE_V, v.v);

        // Draw a larger square (of size 'size')        
        final int size = 2;
        for (int i = -size; i <= size; i++) {
            for (int j = -size; j <= size; j++) {
                f.setPosition(x1 + i, y1 + j);

                consumer.consume(f);
            }
        }
    }

    /**
      * Rasterizes the edge between the projected vectors v1 and v2.
      * Generates Fragment's and calls the Shader::shade() method on
      * each of them.
      * The Fragment's are generated by linearly interpolating the
      * attributes of v1 and v2.
      *
      * @param v1 the first vertex of the edge
      * @param v2 the second vertex of the edge
      */
    public void rasterizeEdge(Vertex v1, Vertex v2) {
        // This is basically Bresenham's algorithm
        final int x1 = v1.x;
        final int y1 = v1.y;
        final int x2 = v2.x;
        final int y2 = v2.y;

        Fragment fragment = new Fragment(0, 0);
        Bresenham.getLine(x1, y1, x2, y2, (x, y) -> {
            fragment.setPosition(x, y);
            Interpolation.interpolate2(v1, v2, fragment, MIDDLE_DOUBLE_VALUE);
            consumer.consume(fragment);
        });

    }

    /**
     * Computes the signed area of the triangle defined by the three vertices v1,
     * v2 and v3.
     *
     * @param v1 the first vertex of the triangle
     * @param v2 the second vertex of the triangle
     * @param v3 the third vertex of the triangle
     * @return the signed area of the triangle
     */
    public static double triangleArea(Vertex v1, Vertex v2, Vertex v3) {
        return (double) v2.x * v3.y - v2.y * v3.x
                + v3.x * v1.y - v1.x * v3.y
                + v1.x * v2.y - v2.x * v1.y;
    }

    /**
     * Computes the barycentric coordinates matrix of the triangle defined by the
     * three vertices v1, v2 and v3.
     *
     * @param v1 the first vertex of the triangle
     * @param v2 the second vertex of the triangle
     * @param v3 the third vertex of the triangle
     * @return the barycentric coordinates matrix of the triangle
     */
    protected static Matrix makeBarycentricCoordsMatrix(final Vertex v1,
                                                        final Vertex v2,
                                                        final Vertex v3) {
        final int squareSize = 3;
        Matrix cMat = new Matrix(squareSize, squareSize);

        final double area = triangleArea(v1, v2, v3);
        final int x1 = v1.x;
        final int y1 = v1.y;
        final int x2 = v2.x;
        final int y2 = v2.y;
        final int x3 = v3.x;
        final int y3 = v3.y;
        cMat.set(0, 0, (x2 * y3 - x3 * y2) / area);
        cMat.set(0, 1, (y2 - y3) / area);
        cMat.set(0, 2, (x3 - x2) / area);
        cMat.set(1, 0, (x3 * y1 - x1 * y3) / area);
        cMat.set(1, 1, (y3 - y1) / area);
        cMat.set(1, 2, (x1 - x3) / area);
        cMat.set(2, 0, (x1 * y2 - x2 * y1) / area);
        cMat.set(2, 1, (y1 - y2) / area);
        cMat.set(2, 2, (x2 - x1) / area);

        return cMat;
    }

    /**
     * Rasterizes the triangular face made of the Fragment v1, v2 and v3.
     *
     * @param v1 the first vertex of the triangle
     * @param v2 the second vertex of the triangle
     * @param v3 the third vertex of the triangle
     * @param onlyDepth a boolean to indicate if the rasterizer should calculate
     *                  all the fragment's attributes or only its depth
     * @throws SizeMismatchException if the size of the Fragment is not correct.
     */
    public void rasterizeFace(Vertex v1, Vertex v2, Vertex v3, boolean onlyDepth)
            throws SizeMismatchException {

        // early exit if the triangle is too small
        final double minArea = 1e-6;
        if (Math.abs(triangleArea(v1, v2, v3)) < minArea) {
            return;
        }
        final Matrix cMat = makeBarycentricCoordsMatrix(v1, v2, v3);

        // iterate over the triangle's bounding box
        //++ // TODO
        //<!!
        final int xmin = Math.min(v1.x, Math.min(v2.x, v3.x));
        final int ymin = Math.min(v1.y, Math.min(v2.y, v3.y));
        final int xmax = Math.max(v1.x, Math.max(v2.x, v3.x));
        final int ymax = Math.max(v1.y, Math.max(v2.y, v3.y));

        // small epsilon to avoid numerical issues on the edges
        final double eps = (new Vector(ymax - ymin, xmax - xmin)).norm() / 1e6;
        final Fragment fragment = new Fragment(0, 0);
        AttributeInterpolator interp = new LinearInterpolator();

        for (int x = xmin; x <= xmax; x++) {
            for (int y = ymin; y <= ymax; y++) {

                final Vector v = new Vector(1.0, x, y);
                final Vector bar = cMat.multiply(v);
                // skip the fragment if outside the triangle
                if (bar.get(0) < -eps || bar.get(1) < -eps || bar.get(2) < -eps) {
                    continue;
                }
                fragment.setPosition(x, y);
                // We will new interpolate all the attributes of the vertices 
                // to calculate those of the fragment
                if(!onlyDepth) {
                    Interpolation.interpolate3(v1, v2, v3, fragment, bar.get(0), bar.get(1), bar.get(2), interp);
                    // The backup code would be here
                } else {
                    final double bias = 1.01;

                    Vector vecAtt = new Vector(v1.depth, v2.depth, v3.depth);
                    double interpolated = bar.dot(vecAtt);
                    fragment.setAttribute(Fragment.DEPTH, interpolated * bias);
                }
                consumer.consume(fragment);
            }
        }
        //>!!
    }
}
