package renderer.core.pipeline;

import renderer.algebra.Matrix;
import renderer.algebra.Vector;
import renderer.algebra.MathUtils;
import renderer.algebra.SizeMismatchException;
import renderer.core.shader.Fragment;
import renderer.utils.Interpolation;
import renderer.utils.Bresenham;

/**
 * The Rasterizer class is responsible for the discretization of geometric
 * primitives (edges and faces) over the screen pixel grid and generates Fragment 
 * (pixels with interpolated attributes). 
 * 
 * Those Fragment are then passed to a FragmentConsumer object,
 * which will produce the final color of the fragment.
 *
 * @author morin, chambon, cdehais, kieliszak
 */
public class Rasterizer {

    /**
     * The default value for interpolate between 2 points.
     */
    private static final double MIDDLE_DOUBLE_VALUE = .5;

    /** The FragmentConsumer to use */
    protected FragmentConsumer consumer;

    /**
     * Creates a Rasterizer with the given FragmentConsumer.
     *
     * @param consumer the fragment consumer to use
     */
    public Rasterizer(FragmentConsumer consumer) {
        this.consumer = consumer;
    }

    public void setConsumer(FragmentConsumer consumer) {
        this.consumer = consumer;
    }


    /**
     * Rasterizes a vertex on the screen.
     *
     * @param v the fragment drawn
     */
    public void rasterizeVertex(final Fragment v) {

        int x1 = v.getX();
        int y1 = v.getY();

        // For now : just display the vertices
        Fragment f = v.clone();;
        final int size = 2;
        for (int i = 0; i < v.getNumAttributes(); i++) {
            f.setAttribute(i, v.getAttribute(i));
        }
        for (int i = -size; i <= size; i++) {
            for (int j = -size; j <= size; j++) {
                f.setPosition(x1 + i, y1 + j);

                consumer.consume(f);
            }
        }
    }

    /**
      * Rasterizes the edge between the projected vectors v1 and v2.
      * Generates Fragment's and calls the Shader::shade() method on
      * each of them.
      * The Fragment's are generated by linearly interpolating the
      * attributes of v1 and v2.
      *
      * @param v1 the first vertex of the edge
      * @param v2 the second vertex of the edge
      */
    public void rasterizeEdge(Fragment v1, Fragment v2) {
        // This is basically Bresenham's algorithm
        final int x1 = v1.getX();
        final int y1 = v1.getY();
        final int x2 = v2.getX();
        final int y2 = v2.getY();

        Fragment fragment = new Fragment(0, 0);
        Bresenham.getLine(x1, y1, x2, y2, (x, y) -> {
            fragment.setPosition(x, y);
            Interpolation.interpolate2(v1, v2, fragment, MIDDLE_DOUBLE_VALUE);
            consumer.consume(fragment);
        });

    }

    /**
     * Computes the signed area of the triangle defined by the three vertices v1,
     * v2 and v3.
     *
     * @param v1 the first vertex of the triangle
     * @param v2 the second vertex of the triangle
     * @param v3 the third vertex of the triangle
     * @return the signed area of the triangle
     */
    static double triangleArea(Fragment v1, Fragment v2, Fragment v3) {
        return (double) v2.getX() * v3.getY() - v2.getY() * v3.getX()
                + v3.getX() * v1.getY() - v1.getX() * v3.getY()
                + v1.getX() * v2.getY() - v2.getX() * v1.getY();
    }

    /**
     * Computes the barycentric coordinates matrix of the triangle defined by the
     * three vertices v1, v2 and v3.
     *
     * @param v1 the first vertex of the triangle
     * @param v2 the second vertex of the triangle
     * @param v3 the third vertex of the triangle
     * @return the barycentric coordinates matrix of the triangle
     */
    protected static Matrix makeBarycentricCoordsMatrix(final Fragment v1,
            final Fragment v2,
            final Fragment v3) {
        final int squareSize = 3;
        Matrix cMat = new Matrix(squareSize, squareSize);

        final double area = triangleArea(v1, v2, v3);
        final int x1 = v1.getX();
        final int y1 = v1.getY();
        final int x2 = v2.getX();
        final int y2 = v2.getY();
        final int x3 = v3.getX();
        final int y3 = v3.getY();
        cMat.set(0, 0, (x2 * y3 - x3 * y2) / area);
        cMat.set(0, 1, (y2 - y3) / area);
        cMat.set(0, 2, (x3 - x2) / area);
        cMat.set(1, 0, (x3 * y1 - x1 * y3) / area);
        cMat.set(1, 1, (y3 - y1) / area);
        cMat.set(1, 2, (x1 - x3) / area);
        cMat.set(2, 0, (x1 * y2 - x2 * y1) / area);
        cMat.set(2, 1, (y1 - y2) / area);
        cMat.set(2, 2, (x2 - x1) / area);

        return cMat;
    }

    /**
     * Rasterizes the triangular face made of the Fragment v1, v2 and v3.
     *
     * @param v1 the first vertex of the triangle
     * @param v2 the second vertex of the triangle
     * @param v3 the third vertex of the triangle
     * @throws SizeMismatchException if the size of the Fragment is not correct.
     */
    public void rasterizeFace(Fragment v1, Fragment v2, Fragment v3, boolean onlyDepth)
            throws SizeMismatchException {

        // early exit if the triangle is too small
        final double minArea = 1e-6;
        if (Math.abs(triangleArea(v1, v2, v3)) < minArea) {
            return;
        }
        final Matrix cMat = makeBarycentricCoordsMatrix(v1, v2, v3);

        // iterate over the triangle's bounding box
        //++ // TODO
        //<!!
        final int xmin = Math.min(v1.getX(), Math.min(v2.getX(), v3.getX()));
        final int ymin = Math.min(v1.getY(), Math.min(v2.getY(), v3.getY()));
        final int xmax = Math.max(v1.getX(), Math.max(v2.getX(), v3.getX()));
        final int ymax = Math.max(v1.getY(), Math.max(v2.getY(), v3.getY()));

        // small epsilon to avoid numerical issues on the edges
        final double eps = (new Vector(ymax - ymin, xmax - xmin)).norm() / 1e6;
        final Fragment fragment = new Fragment(0, 0);
        final int numAttributes = fragment.getNumAttributes();

        for (int x = xmin; x <= xmax; x++) {
            for (int y = ymin; y <= ymax; y++) {

                final Vector v = new Vector(1.0, x, y);
                final Vector bar = cMat.multiply(v);
                // skip the fragment if outside the triangle
                if (bar.get(0) < -eps || bar.get(1) < -eps || bar.get(2) < -eps) {
                    continue;
                }
                fragment.setPosition(x, y);
                if(!onlyDepth) {
                    for (int i = 0; i < numAttributes; i++) {
                        // get the attributes in a vector
                        final Vector vecAtt = new Vector(v1.getAttribute(i),
                                                        v2.getAttribute(i),
                                                        v3.getAttribute(i));
                        // interpolate the attributes
                        double interpolated = bar.dot(vecAtt);
                        // for the color attribute (indices ranging from COLOR_R to COLOR_B)
                        if (i >= Fragment.COLOR_R && i <= Fragment.COLOR_ALPHA) {
                            // clamp the color between 0 and 1;
                            interpolated = MathUtils.clamp(interpolated, 0, 1);
                        }
                        fragment.setAttribute(i, interpolated);
                    }
                } else {
                    final double bias = 1.01;

                    final Vector vecAtt = new Vector(v1.getAttribute(Fragment.DEPTH),
                                                     v2.getAttribute(Fragment.DEPTH),
                                                     v3.getAttribute(Fragment.DEPTH));
                    double interpolated = bar.dot(vecAtt);
                    fragment.setAttribute(Fragment.DEPTH, interpolated * bias);
                }
                consumer.consume(fragment.clone());
            }
        }
        //>!!
    }
}
